trigger:
- 'main'

stages:
- stage: E2ETest
  displayName: E2E Tests
  jobs:
  - job: e2e_tests
    container:
      image: mcr.microsoft.com/playwright:focal
      
    steps:
      - checkout: self

      - task: Npm@1
        inputs:
          command: 'install'
        displayName: 'installing dependencies'

# using CmdLine instead of Npm because npm buffers the entire output
      - task: CmdLine@2
        displayName: 'Running e2e tests'
        inputs:
          script: npm run test-e2e account-login/en
